Backup failed for Site airline.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['airline.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x106f40400>
      exit_code = 0
      rollback_callback = None
      site = 'airline.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10714c7c0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10714c7c0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x10711b390>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x10711b390>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x10711b390>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10711b390>>
      paths = ('./airline.local/private/backups/20250513_180001-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250513_180001-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x10711b390>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10711b390>>
      paths = ('./airline.local/private/backups/20250513_180001-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250513_180001-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x10711b390>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x107151f80>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./airline.local/private/backups/20250513_180001-airline_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x106f59bc0>
      bin = None
      args = ['--user=_4487886e7fe82f5c', '--host=127.0.0.1', '--port=3306', '--password=7wt3HlMog05xAUCP', '--single-transaction', '--quick', '--lock-tables=false', '_4487886e7fe82f5c']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x107150fe0>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'f27441e0907e02ae8f526c9266ec5b92a523a7aa1f37c1d22d51cc50'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'f27441e0907e02ae8f526c9266ec5b92a523a7aa1f37c1d22d51cc50'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site airline.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['airline.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x105b64400>
      exit_code = 0
      rollback_callback = None
      site = 'airline.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105d707c0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105d707c0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x105d5c9d0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x105d5c9d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x105d5c9d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105d5c9d0>>
      paths = ('./airline.local/private/backups/20250514_000003-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250514_000003-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x105d5c9d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x105d5c9d0>>
      paths = ('./airline.local/private/backups/20250514_000003-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250514_000003-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x105d5c9d0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x105d75f80>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./airline.local/private/backups/20250514_000003-airline_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x105b7dbc0>
      bin = None
      args = ['--user=_4487886e7fe82f5c', '--host=127.0.0.1', '--port=3306', '--password=7wt3HlMog05xAUCP', '--single-transaction', '--quick', '--lock-tables=false', '_4487886e7fe82f5c']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x105d74fe0>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '9f7444a4558273d837ce769e65310fe79ad087f36e3068fadeff2a18'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '9f7444a4558273d837ce769e65310fe79ad087f36e3068fadeff2a18'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site airline.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['airline.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x104da8400>
      exit_code = 0
      rollback_callback = None
      site = 'airline.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104fb47c0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104fb47c0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x104fa0890>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x104fa0890>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x104fa0890>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104fa0890>>
      paths = ('./airline.local/private/backups/20250514_120001-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250514_120001-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x104fa0890>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104fa0890>>
      paths = ('./airline.local/private/backups/20250514_120001-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250514_120001-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x104fa0890>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x104fb9f80>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./airline.local/private/backups/20250514_120001-airline_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x104dc1bc0>
      bin = None
      args = ['--user=_4487886e7fe82f5c', '--host=127.0.0.1', '--port=3306', '--password=7wt3HlMog05xAUCP', '--single-transaction', '--quick', '--lock-tables=false', '_4487886e7fe82f5c']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x104fb8fe0>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '78d3849940df0bd03380fd6b8bbfa7f34ca6c2956e6d04aa6595b910'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '78d3849940df0bd03380fd6b8bbfa7f34ca6c2956e6d04aa6595b910'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site airline.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['airline.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x103964400>
      exit_code = 0
      rollback_callback = None
      site = 'airline.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103b009a0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103b009a0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x103ade410>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x103ade410>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x103ade410>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103ade410>>
      paths = ('./airline.local/private/backups/20250514_180002-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250514_180002-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x103ade410>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103ade410>>
      paths = ('./airline.local/private/backups/20250514_180002-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250514_180002-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x103ade410>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x1049b72e0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./airline.local/private/backups/20250514_180002-airline_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x10397dbc0>
      bin = None
      args = ['--user=_4487886e7fe82f5c', '--host=127.0.0.1', '--port=3306', '--password=7wt3HlMog05xAUCP', '--single-transaction', '--quick', '--lock-tables=false', '_4487886e7fe82f5c']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10568ca40>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '48ee0356f2bc590651b1c687e58a9fee7678fc94c5153f7bdbdc26bf'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '48ee0356f2bc590651b1c687e58a9fee7678fc94c5153f7bdbdc26bf'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site airline.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['airline.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x104db4400>
      exit_code = 0
      rollback_callback = None
      site = 'airline.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104f8c7c0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x104f8c7c0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x104f789d0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x104f789d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x104f789d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104f789d0>>
      paths = ('./airline.local/private/backups/20250515_000009-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250515_000009-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x104f789d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x104f789d0>>
      paths = ('./airline.local/private/backups/20250515_000009-airline_local-database.sql.gz',)
      path = './airline.local/private/backups/20250515_000009-airline_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x104f789d0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x104f91f80>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./airline.local/private/backups/20250515_000009-airline_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x104dcdbc0>
      bin = None
      args = ['--user=_4487886e7fe82f5c', '--host=127.0.0.1', '--port=3306', '--password=7wt3HlMog05xAUCP', '--single-transaction', '--quick', '--lock-tables=false', '_4487886e7fe82f5c']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x104f90fe0>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'e7aa363ba8924d6c063c15818b717edcce08af0370e4ea6de4f0880e'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'e7aa363ba8924d6c063c15818b717edcce08af0370e4ea6de4f0880e'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
