Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x102c6f240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x102e1bc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x102e1bc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x102e42f10>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x102e42f10>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x102e42f10>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x102e42f10>>
      paths = ('./leave.local/private/backups/20250509_120002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250509_120002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x102e42f10>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x102e42f10>>
      paths = ('./leave.local/private/backups/20250509_120002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250509_120002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x102e42f10>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x102e5d300>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250509_120002-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x102ca8cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x102e5c180>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'bbb1dbfa0b88ecead9669cd09610a51010e0b691500510521778e931'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'bbb1dbfa0b88ecead9669cd09610a51010e0b691500510521778e931'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x102f6b240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10314bc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10314bc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1031727d0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1031727d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1031727d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1031727d0>>
      paths = ('./leave.local/private/backups/20250509_180002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250509_180002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1031727d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1031727d0>>
      paths = ('./leave.local/private/backups/20250509_180002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250509_180002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1031727d0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x103b0eca0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250509_180002-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x102fa4cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10318d940>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'f832a80b9e7e2e7efbf9fd82febc0fad01f31e4bfdb3f8a39bdb9594'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'f832a80b9e7e2e7efbf9fd82febc0fad01f31e4bfdb3f8a39bdb9594'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x105e77240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105febc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105febc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x106112850>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x106112850>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x106112850>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x106112850>>
      paths = ('./leave.local/private/backups/20250510_000002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250510_000002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x106112850>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x106112850>>
      paths = ('./leave.local/private/backups/20250510_000002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250510_000002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x106112850>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x106c92ca0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250510_000002-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x105eb0cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10612d940>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '07dd087949eaf76d8db019d9bb53b50a3e5d5d14afaf3de3d333dc29'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '07dd087949eaf76d8db019d9bb53b50a3e5d5d14afaf3de3d333dc29'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1078e7240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x107ac7c10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x107ac7c10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x107aeb350>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x107aeb350>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x107aeb350>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x107aeb350>>
      paths = ('./leave.local/private/backups/20250510_120002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250510_120002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x107aeb350>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x107aeb350>>
      paths = ('./leave.local/private/backups/20250510_120002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250510_120002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x107aeb350>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x108486ca0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250510_120002-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x10791ccc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x107b05940>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '011cb0f638d6f037712b123ce623f4f2cc352364ab7c53b78f5cf565'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '011cb0f638d6f037712b123ce623f4f2cc352364ab7c53b78f5cf565'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x10355b240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10373bc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10373bc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x103762e50>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x103762e50>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x103762e50>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103762e50>>
      paths = ('./leave.local/private/backups/20250510_180002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250510_180002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x103762e50>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103762e50>>
      paths = ('./leave.local/private/backups/20250510_180002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250510_180002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x103762e50>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x1040feca0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250510_180002-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x103594cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10377d940>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '72c26b447d09fe20c9e4e01be7db04b55bab8b27dad1c711a8f918b2'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '72c26b447d09fe20c9e4e01be7db04b55bab8b27dad1c711a8f918b2'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x107f7b240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1108efc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1108efc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x110912f10>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x110912f10>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x110912f10>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x110912f10>>
      paths = ('./leave.local/private/backups/20250511_120001-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250511_120001-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x110912f10>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x110912f10>>
      paths = ('./leave.local/private/backups/20250511_120001-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250511_120001-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x110912f10>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x110929300>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250511_120001-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x107fb0cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x110928180>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '9b3c2d5fe38f7a9129dce96d76bdc4d12359c2acb7dbf7d06af0588c'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '9b3c2d5fe38f7a9129dce96d76bdc4d12359c2acb7dbf7d06af0588c'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x102f8f240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10316fc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10316fc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x101697890>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x101697890>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x101697890>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x101697890>>
      paths = ('./leave.local/private/backups/20250511_180008-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250511_180008-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x101697890>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x101697890>>
      paths = ('./leave.local/private/backups/20250511_180008-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250511_180008-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x101697890>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x1031ad300>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250511_180008-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x102fc8cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1031ac180>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'dd064b923377384f37496105ef43cd22a329c7ca16492c97fcdda6dd'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'dd064b923377384f37496105ef43cd22a329c7ca16492c97fcdda6dd'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x104f57240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105137c10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x105137c10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x10515eb50>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x10515eb50>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x10515eb50>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10515eb50>>
      paths = ('./leave.local/private/backups/20250512_000002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250512_000002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x10515eb50>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10515eb50>>
      paths = ('./leave.local/private/backups/20250512_000002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250512_000002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x10515eb50>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x105179300>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250512_000002-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x104f90cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x105178180>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '1a4a43b4731e0d6dacbacdde3221c5b21c58eb19913b14734e228099'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '1a4a43b4731e0d6dacbacdde3221c5b21c58eb19913b14734e228099'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1073eb240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1075cbc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1075cbc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1075f3090>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1075f3090>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1075f3090>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1075f3090>>
      paths = ('./leave.local/private/backups/20250512_120001-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250512_120001-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1075f3090>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1075f3090>>
      paths = ('./leave.local/private/backups/20250512_120001-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250512_120001-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1075f3090>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x10760d300>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250512_120001-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x107424cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x10760c180>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '0d704df1b8dc86abca43190d02a3691b2df3f0c808a30bb8c8589a43'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '0d704df1b8dc86abca43190d02a3691b2df3f0c808a30bb8c8589a43'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x103577240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103723df0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103723df0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1032f2410>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1032f2410>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1032f2410>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1032f2410>>
      paths = ('./leave.local/private/backups/20250512_180002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250512_180002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1032f2410>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1032f2410>>
      paths = ('./leave.local/private/backups/20250512_180002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250512_180002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1032f2410>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x1052ba840>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250512_180002-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1035b0cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x105628360>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '7c549fed2e2ac2ffdd4b9917966709437a1484cc000ba95aa441af9b'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '7c549fed2e2ac2ffdd4b9917966709437a1484cc000ba95aa441af9b'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x106d63240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x106f3fdf0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x106f3fdf0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x106f648d0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x106f648d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x106f648d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x106f648d0>>
      paths = ('./leave.local/private/backups/20250513_120002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250513_120002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x106f648d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x106f648d0>>
      paths = ('./leave.local/private/backups/20250513_120002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250513_120002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x106f648d0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x107d4e840>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250513_120002-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x106d98cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1080bc360>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '0dfda241abe13fc11fb4629bbaac578614973a7b2e1c9debb854c9b8'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '0dfda241abe13fc11fb4629bbaac578614973a7b2e1c9debb854c9b8'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x10756b240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x107747c10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x107747c10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x10776ed10>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x10776ed10>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x10776ed10>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10776ed10>>
      paths = ('./leave.local/private/backups/20250513_180002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250513_180002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x10776ed10>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x10776ed10>>
      paths = ('./leave.local/private/backups/20250513_180002-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250513_180002-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x10776ed10>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x10810aca0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250513_180002-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1075a0cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x107785940>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '53f9194f7ff7b8901b2395186fb264ffd39adf2a93f39bc4a6df841d'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '53f9194f7ff7b8901b2395186fb264ffd39adf2a93f39bc4a6df841d'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x103c77240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103defc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x103defc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x103e0f190>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x103e0f190>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x103e0f190>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103e0f190>>
      paths = ('./leave.local/private/backups/20250514_000003-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250514_000003-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x103e0f190>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x103e0f190>>
      paths = ('./leave.local/private/backups/20250514_000003-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250514_000003-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x103e0f190>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x103e29300>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250514_000003-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x103cb0cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x103e28180>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '0df196f749f76c8d9cc36d7f4cf795a040fc23a2f76d27a23cc25c74'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '0df196f749f76c8d9cc36d7f4cf795a040fc23a2f76d27a23cc25c74'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1032a3240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10347fc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10347fc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1034a6650>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1034a6650>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1034a6650>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1034a6650>>
      paths = ('./leave.local/private/backups/20250514_120001-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250514_120001-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1034a6650>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1034a6650>>
      paths = ('./leave.local/private/backups/20250514_120001-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250514_120001-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1034a6650>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x1034bd300>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250514_120001-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1032d8cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1034bc180>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '4a70ddd44041a02a6c38a92b7a3b2c8b5831f07eb94c17c4c7d73f6b'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '4a70ddd44041a02a6c38a92b7a3b2c8b5831f07eb94c17c4c7d73f6b'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1031f3240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1033d7df0>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x1033d7df0>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1033fc750>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1033fc750>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1033fc750>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1033fc750>>
      paths = ('./leave.local/private/backups/20250514_180003-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250514_180003-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1033fc750>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1033fc750>>
      paths = ('./leave.local/private/backups/20250514_180003-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250514_180003-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1033fc750>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x1041e6840>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250514_180003-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x10322ccc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x104550360>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'c58841ee8dee55a85b6d5cbbd501ae3227f3c92a51e14f5a01a6be4c'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': 'c58841ee8dee55a85b6d5cbbd501ae3227f3c92a51e14f5a01a6be4c'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
Backup failed for Site leave.local. Database or site_config.json may be corrupted
Traceback with variables (most recent call last):
  File "apps/frappe/frappe/commands/site.py", line 865, in backup
    odb = scheduled_backup(
      context = CliCtxObj(sites=['leave.local'], force=False, profile=False, verbose=True)
      with_files = False
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_backup_conf = False
      verbose = True
      compress = False
      include = ''
      exclude = ''
      old_backup_metadata = False
      scheduled_backup = <function scheduled_backup at 0x1070ab240>
      exit_code = 0
      rollback_callback = None
      site = 'leave.local'
  File "apps/frappe/frappe/utils/backups.py", line 589, in scheduled_backup
    return new_backup(
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10728bc10>
  File "apps/frappe/frappe/utils/backups.py", line 647, in new_backup
    odb.get_backup(older_than, ignore_files, force=force)
      older_than = 6
      ignore_files = True
      backup_path = None
      backup_path_db = None
      backup_path_files = None
      backup_path_private_files = None
      backup_path_conf = None
      ignore_conf = False
      include_doctypes = ''
      exclude_doctypes = ''
      compress = False
      force = True
      verbose = True
      old_backup_metadata = False
      rollback_callback = <frappe.utils.CallbackManager object at 0x10728bc10>
      odb = <frappe.utils.backups.BackupGenerator object at 0x1072b27d0>
  File "apps/frappe/frappe/utils/backups.py", line 191, in get_backup
    self.delete_if_step_fails(self.take_dump, self.backup_path_db)
      self = <frappe.utils.backups.BackupGenerator object at 0x1072b27d0>
      older_than = 6
      ignore_files = True
      force = True
      last_db = False
      last_file = False
      last_private_file = False
      site_config_backup_path = False
  File "apps/frappe/frappe/utils/backups.py", line 528, in delete_if_step_fails
    raise e
      self = <frappe.utils.backups.BackupGenerator object at 0x1072b27d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1072b27d0>>
      paths = ('./leave.local/private/backups/20250515_000011-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250515_000011-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 523, in delete_if_step_fails
    step()
      self = <frappe.utils.backups.BackupGenerator object at 0x1072b27d0>
      step = <bound method BackupGenerator.take_dump of <frappe.utils.backups.BackupGenerator object at 0x1072b27d0>>
      paths = ('./leave.local/private/backups/20250515_000011-leave_local-database.sql.gz',)
      path = './leave.local/private/backups/20250515_000011-leave_local-database.sql.gz'
  File "apps/frappe/frappe/utils/backups.py", line 465, in take_dump
    frappe.throw(
      self = <frappe.utils.backups.BackupGenerator object at 0x1072b27d0>
      frappe = <module 'frappe' from 'apps/frappe/frappe/__init__.py'>
      shlex = <module 'shlex' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/shlex.py'>
      get_app_branch = <function get_app_branch at 0x107c4eca0>
      gzip_exc = '/usr/bin/gzip'
      database_header_content = ['begin frappe metadata', '[frappe]', 'version = 16.0.0-dev', 'branch = develop', 'end frappe metadata', '']
      generated_header = '-- begin frappe metadata\n-- [frappe]\n-- version = 16.0.0-dev\n-- branch = develop\n-- end frappe metadata\n-- \n'
      f = <_io.TextIOWrapper name='./leave.local/private/backups/20250515_000011-leave_local-database.sql.gz' encoding='UTF-8'>
      cmd = []
      extra = []
      get_command = <function get_command at 0x1070e4cc0>
      bin = None
      args = ['--user=_3a949fb2dad955d3', '--host=127.0.0.1', '--port=3306', '--password=hnain4LxyMUUH5IL', '--single-transaction', '--quick', '--lock-tables=false', '_3a949fb2dad955d3']
      bin_name = 'mariadb-dump'
  File "apps/frappe/frappe/utils/messages.py", line 145, in throw
    msgprint(
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      exc = <class 'frappe.exceptions.ExecutableNotFound'>
      title = None
      is_minimizable = False
      wide = False
      as_list = False
      primary_action = None
  File "apps/frappe/frappe/utils/messages.py", line 106, in msgprint
    _raise_exception()
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      title = None
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
      as_table = False
      as_list = False
      indicator = 'red'
      alert = False
      primary_action = None
      is_minimizable = False
      wide = False
      realtime = False
      _raise_exception = <function msgprint.<locals>._raise_exception at 0x1072cd940>
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '80b39824ecfcc20ccdc59d8e7079f3401b14ffe67e3584bc9e35dd4a'}
  File "apps/frappe/frappe/utils/messages.py", line 57, in _raise_exception
    raise exc
      exc = ExecutableNotFound('mariadb-dump not found in PATH! This is required to take a backup.')
      inspect = <module 'inspect' from '/Users/upforcetech/.pyenv/versions/3.11.8/lib/python3.11/inspect.py'>
      msg = 'mariadb-dump not found in PATH! This is required to take a backup.'
      out = {'message': 'mariadb-dump not found in PATH! This is required to take a backup.', 'title': 'Message', 'indicator': 'red', 'raise_exception': 1, '__frappe_exc_id': '80b39824ecfcc20ccdc59d8e7079f3401b14ffe67e3584bc9e35dd4a'}
      raise_exception = <class 'frappe.exceptions.ExecutableNotFound'>
frappe.exceptions.ExecutableNotFound: mariadb-dump not found in PATH! This is required to take a backup.
